name: pub_cache_browser
description: List all packages in HOME/.pub_cache and provide some useful actions
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  bot_toast: ^4.1.3
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  desktop_multi_window: ^0.2.1
  equatable: ^2.0.7
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_markdown: ^0.7.7+1
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.1.0
  #  macos_ui: 1.7.6
  macos_ui: ^2.2.0
  material_design_icons_flutter: ^7.0.7296
  meta: ^1.16.0
  mixin_logger: ^0.1.2
  path: ^1.8.1
  path_provider: ^2.1.5
  provider: ^6.1.5
  pub_semver: ^2.2.0
  shared_preferences: ^2.5.3
  tuple: ^2.0.2
  yaml: ^3.1.3

dependency_overrides:
  xml: ^6.5.0
  collection: ^1.19.1

dev_dependencies:
  build_runner: ^2.6.0
  custom_lint: ^0.7.6
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
